syscalls = {

    "read"                  : { "id": 0, "threat": 3},
    "write"                 : { "id": 1, "threat": 3},
    "open"                  : { "id": 2, "threat": 1},
    "close"                 : { "id": 3, "threat": 3},
    "stat"                  : { "id": 4, "threat": 4},
    "fstat"                 : { "id": 5, "threat": 4},
    "lstat"                 : { "id": 6, "threat": 4},
    "poll"                  : { "id": 7, "threat": 3},
    "lseek"                 : { "id": 8, "threat": 3},
    "mmap"                  : { "id": 9, "threat": 3},
    "mprotect"              : { "id": 10, "threat": 3},
    "munmap"                : { "id": 11, "threat": 3},
    "brk"                   : { "id": 12, "threat": 2},
    "rt_sigaction"          : { "id": 13, "threat": 3},
    "rt_sigprocmask"        : { "id": 14, "threat": 3},
    "rt_sigreturn"          : { "id": 15, "threat": 3},
    "ioctl"                 : { "id": 16, "threat": 2},
    "pread64"               : { "id": 17, "threat": 3},
    "pwrite64"              : { "id": 18, "threat": 3},
    "readv"                 : { "id": 19, "threat": 3},
    "writev"                : { "id": 20, "threat": 3},
    "access"                : { "id": 21, "threat": 4},
    "pipe"                  : { "id": 22, "threat": 4},
    "select"                : { "id": 23, "threat": 3},
    "sched_yield"           : { "id": 24, "threat": 3},
    "mremap"                : { "id": 25, "threat": 3},
    "msync"                 : { "id": 26, "threat": 3},
    "mincore"               : { "id": 27, "threat": 1},
    "madvise"               : { "id": 28, "threat": 6},
    "shmget"                : { "id": 29},
    "shmat"                 : { "id": 30},
    "shmctl"                : { "id": 31},
    "dup"                   : { "id": 32, "threat": 3},
    "dup2"                  : { "id": 33, "threat": 2},
    "pause"                 : { "id": 34, "threat": 3},
    "nanosleep"             : { "id": 35, "threat": 3},
    "getitimer"             : { "id": 36},
    "alarm"                 : { "id": 37},
    "setitimer"             : { "id": 38, "threat": 4},
    "getpid"                : { "id": 39, "threat": 4},
    "sendfile"              : { "id": 40},
    "socket"                : { "id": 41, "threat": 6},
    "connect"               : { "id": 42, "threat": 6},
    "accept"                : { "id": 43, "threat": 6},
    "sendto"                : { "id": 44, "threat": 6},
    "recvfrom"              : { "id": 45, "threat": 6},
    "sendmsg"               : { "id": 46},
    "recvmsg"               : { "id": 47, "threat": 6},
    "shutdown"              : { "id": 48, "threat": 6},
    "bind"                  : { "id": 49, "threat": 6},
    "listen"                : { "id": 50},
    "getsockname"           : { "id": 51, "threat": 6},
    "getpeername"           : { "id": 52, "threat": 6},
    "socketpair"            : { "id": 53},
    "setsockopt"            : { "id": 54, "threat": 6},
    "getsockopt"            : { "id": 55, "threat": 6},
    "clone"                 : { "id": 56, "threat": 2},
    "fork"                  : { "id": 57},
    "vfork"                 : { "id": 58},
    "execve"                : { "id": 59},
    "exit"                  : { "id": 60},
    "wait4"                 : { "id": 61, "threat": 3},
    "kill"                  : { "id": 62},
    "uname"                 : { "id": 63, "threat": 4},
    "semget"                : { "id": 64},
    "semop"                 : { "id": 65},
    "semctl"                : { "id": 66},
    "shmdt"                 : { "id": 67},
    "msgget"                : { "id": 68},
    "msgsnd"                : { "id": 69},
    "msgrcv"                : { "id": 70},
    "msgctl"                : { "id": 71},
    "fcntl"                 : { "id": 72, "threat": 3},
    "flock"                 : { "id": 73, "threat": 2},
    "fsync"                 : { "id": 74},
    "fdatasync"             : { "id": 75},
    "truncate"              : { "id": 76},
    "ftruncate"             : { "id": 77},
    "getdents"              : { "id": 78, "threat": 4},
    "getcwd"                : { "id": 79, "threat": 4},
    "chdir"                 : { "id": 80, "threat": 3},
    "fchdir"                : { "id": 81},
    "rename"                : { "id": 82, "threat": 1},
    "mkdir"                 : { "id": 83},
    "rmdir"                 : { "id": 84},
    "creat"                 : { "id": 85},
    "link"                  : { "id": 86},
    "unlink"                : { "id": 87, "threat": 1},
    "symlink"               : { "id": 88},
    "readlink"              : { "id": 89},
    "chmod"                 : { "id": 90, "threat": 1},
    "fchmod"                : { "id": 91},
    "chown"                 : { "id": 92},
    "fchown"                : { "id": 93},
    "lchown"                : { "id": 94},
    "umask"                 : { "id": 95, "threat": 3},
    "gettimeofday"          : { "id": 96},
    "getrlimit"             : { "id": 97},
    "getrusage"             : { "id": 98},
    "sysinfo"               : { "id": 99},
    "times"                 : { "id": 100, "threat": 4},
    "ptrace"                : { "id": 101},
    "getuid"                : { "id": 102},
    "syslog"                : { "id": 103},
    "getgid"                : { "id": 104},
    "setuid"                : { "id": 105},
    "setgid"                : { "id": 106},
    "geteuid"               : { "id": 107},
    "getegid"               : { "id": 108},
    "setpgid"               : { "id": 109},
    "getppid"               : { "id": 110},
    "getpgrp"               : { "id": 111},
    "setsid"                : { "id": 112},
    "setreuid"              : { "id": 113},
    "setregid"              : { "id": 114},
    "getgroups"             : { "id": 115},
    "setgroups"             : { "id": 116},
    "setresuid"             : { "id": 117},
    "getresuid"             : { "id": 118},
    "setresgid"             : { "id": 119},
    "getresgid"             : { "id": 120},
    "getpgid"               : { "id": 121},
    "setfsuid"              : { "id": 122},
    "setfsgid"              : { "id": 123},
    "getsid"                : { "id": 124},
    "capget"                : { "id": 125},
    "capset"                : { "id": 126},
    "rt_sigpending"         : { "id": 127},
    "rt_sigtimedwait"       : { "id": 128},
    "rt_sigqueueinfo"       : { "id": 129},
    "rt_sigsuspend"         : { "id": 130},
    "sigaltstack"           : { "id": 131},
    "utime"                 : { "id": 132},
    "mknod"                 : { "id": 133},
    "uselib"                : { "id": 134},
    "personality"           : { "id": 135},
    "ustat"                 : { "id": 136},
    "statfs"                : { "id": 137},
    "fstatfs"               : { "id": 138},
    "sysfs"                 : { "id": 139},
    "getpriority"           : { "id": 140},
    "setpriority"           : { "id": 141},
    "sched_setparam"        : { "id": 142},
    "sched_getparam"        : { "id": 143},
    "sched_setscheduler"    : { "id": 144},
    "sched_getscheduler"    : { "id": 145},
    "sched_get_priority_max": { "id": 146},
    "sched_get_priority_min": { "id": 147},
    "sched_rr_get_interval" : { "id": 148},
    "mlock"                 : { "id": 149},
    "munlock"               : { "id": 150},
    "mlockall"              : { "id": 151},
    "munlockall"            : { "id": 152},
    "vhangup"               : { "id": 153},
    "modify_ldt"            : { "id": 154},
    "pivot_root"            : { "id": 155},
    "_sysctl"               : { "id": 156},
    "prctl"                 : { "id": 157},
    "arch_prctl"            : { "id": 158},
    "adjtimex"              : { "id": 159},
    "setrlimit"             : { "id": 160},
    "chroot"                : { "id": 161},
    "sync"                  : { "id": 162},
    "acct"                  : { "id": 163},
    "settimeofday"          : { "id": 164},
    "mount"                 : { "id": 165},
    "umount2"               : { "id": 166},
    "swapon"                : { "id": 167},
    "swapoff"               : { "id": 168},
    "reboot"                : { "id": 169},
    "sethostname"           : { "id": 170},
    "setdomainname"         : { "id": 171},
    "iopl"                  : { "id": 172},
    "ioperm"                : { "id": 173},
    "create_module"         : { "id": 174},
    "init_module"           : { "id": 175},
    "delete_module"         : { "id": 176},
    "get_kernel_syms"       : { "id": 177},
    "query_module"          : { "id": 178},
    "quotactl"              : { "id": 179},
    "nfsservctl"            : { "id": 180},
    "getpmsg"               : { "id": 181},
    "putpmsg"               : { "id": 182},
    "afs_syscall"           : { "id": 183},
    "tuxcall"               : { "id": 184},
    "security"              : { "id": 185},
    "gettid"                : { "id": 186},
    "readahead"             : { "id": 187},
    "setxattr"              : { "id": 188},
    "lsetxattr"             : { "id": 189},
    "fsetxattr"             : { "id": 190},
    "getxattr"              : { "id": 191},
    "lgetxattr"             : { "id": 192},
    "fgetxattr"             : { "id": 193},
    "listxattr"             : { "id": 194},
    "llistxattr"            : { "id": 195},
    "flistxattr"            : { "id": 196},
    "removexattr"           : { "id": 197},
    "lremovexattr"          : { "id": 198},
    "fremovexattr"          : { "id": 199},
    "tkill"                 : { "id": 200},
    "time"                  : { "id": 201},
    "futex"                 : { "id": 202, "threat": 6},
    "sched_setaffinity"     : { "id": 203},
    "sched_getaffinity"     : { "id": 204},
    "set_thread_area"       : { "id": 205},
    "io_setup"              : { "id": 206},
    "io_destroy"            : { "id": 207},
    "io_getevents"          : { "id": 208},
    "io_submit"             : { "id": 209},
    "io_cancel"             : { "id": 210},
    "get_thread_area"       : { "id": 211},
    "lookup_dcookie"        : { "id": 212},
    "epoll_create"          : { "id": 213},
    "epoll_ctl_old"         : { "id": 214},
    "epoll_wait_old"        : { "id": 215},
    "remap_file_pages"      : { "id": 216},
    "getdents64"            : { "id": 217},
    "set_tid_address"       : { "id": 218},
    "restart_syscall"       : { "id": 219},
    "semtimedop"            : { "id": 220},
    "fadvise64"             : { "id": 221},
    "timer_create"          : { "id": 222},
    "timer_settime"         : { "id": 223},
    "timer_gettime"         : { "id": 224},
    "timer_getoverrun"      : { "id": 225},
    "timer_delete"          : { "id": 226},
    "clock_settime"         : { "id": 227},
    "clock_gettime"         : { "id": 228},
    "clock_getres"          : { "id": 229},
    "clock_nanosleep"       : { "id": 230},
    "exit_group"            : { "id": 231},
    "epoll_wait"            : { "id": 232},
    "epoll_ctl"             : { "id": 233},
    "tgkill"                : { "id": 234},
    "utimes"                : { "id": 235},
    "vserver"               : { "id": 236},
    "mbind"                 : { "id": 237},
    "set_mempolicy"         : { "id": 238},
    "get_mempolicy"         : { "id": 239},
    "mq_open"               : { "id": 240},
    "mq_unlink"             : { "id": 241},
    "mq_timedsend"          : { "id": 242},
    "mq_timedreceive"       : { "id": 243},
    "mq_notify"             : { "id": 244},
    "mq_getsetattr"         : { "id": 245},
    "kexec_load"            : { "id": 246},
    "waitid"                : { "id": 247},
    "add_key"               : { "id": 248},
    "request_key"           : { "id": 249},
    "keyctl"                : { "id": 250},
    "ioprio_set"            : { "id": 251},
    "ioprio_get"            : { "id": 252},
    "inotify_init"          : { "id": 253},
    "inotify_add_watch"     : { "id": 254},
    "inotify_rm_watch"      : { "id": 255},
    "migrate_pages"         : { "id": 256},
    "openat"                : { "id": 257},
    "mkdirat"               : { "id": 258},
    "mknodat"               : { "id": 259},
    "fchownat"              : { "id": 260},
    "futimesat"             : { "id": 261},
    "newfstatat"            : { "id": 262},
    "unlinkat"              : { "id": 263},
    "renameat"              : { "id": 264},
    "linkat"                : { "id": 265},
    "symlinkat"             : { "id": 266},
    "readlinkat"            : { "id": 267},
    "fchmodat"              : { "id": 268},
    "faccessat"             : { "id": 269},
    "pselect6"              : { "id": 270},
    "ppoll"                 : { "id": 271},
    "unshare"               : { "id": 272},
    "set_robust_list"       : { "id": 273},
    "get_robust_list"       : { "id": 274},
    "splice"                : { "id": 275},
    "tee"                   : { "id": 276},
    "sync_file_range"       : { "id": 277},
    "vmsplice"              : { "id": 278},
    "move_pages"            : { "id": 279},
    "utimensat"             : { "id": 280},
    "epoll_pwait"           : { "id": 281},
    "signalfd"              : { "id": 282},
    "timerfd_create"        : { "id": 283},
    "eventfd"               : { "id": 284},
    "fallocate"             : { "id": 285},
    "timerfd_settime"       : { "id": 286},
    "timerfd_gettime"       : { "id": 287},
    "accept4"               : { "id": 288, "threat": 6},
    "signalfd4"             : { "id": 289},
    "eventfd2"              : { "id": 290},
    "epoll_create1"         : { "id": 291},
    "dup3"                  : { "id": 292},
    "pipe2"                 : { "id": 293, "threat": 6},
    "inotify_init1"         : { "id": 294},
    "preadv"                : { "id": 295},
    "pwritev"               : { "id": 296},
    "rt_tgsigqueueinfo"     : { "id": 297},
    "perf_event_open"       : { "id": 298},
    "recvmmsg"              : { "id": 299},
    "fanotify_init"         : { "id": 300},
    "fanotify_mark"         : { "id": 301},
    "prlimit64"             : { "id": 302},
    "name_to_handle_at"     : { "id": 303},
    "open_by_handle_at"     : { "id": 304},
    "clock_adjtime"         : { "id": 305},
    "syncfs"                : { "id": 306},
    "sendmmsg"              : { "id": 307, "threat": 6},
    "setns"                 : { "id": 308},
    "getcpu"                : { "id": 309},
    "process_vm_readv"      : { "id": 310},
    "process_vm_writev"     : { "id": 311},
    "kcmp"                  : { "id": 312},
    "finit_module"          : { "id": 313},
    "sched_setattr"         : { "id": 314},
    "sched_getattr"         : { "id": 315},
    "renameat2"             : { "id": 316},
    "seccomp"               : { "id": 317},
    "getrandom"             : { "id": 318, "threat": 6},
    "memfd_create"          : { "id": 319},
    "kexec_file_load"       : { "id": 320},
    "bpf"                   : { "id": 321},
    "execveat"              : { "id": 322},
    "userfaultfd"           : { "id": 323},
    "membarrier"            : { "id": 324},
    "mlock2"                : { "id": 325},
    "copy_file_range"       : { "id": 326},
    "preadv2"               : { "id": 327},
    "pwritev2"              : { "id": 328},
    "pkey_mprotect"         : { "id": 329},
    "pkey_alloc"            : { "id": 330},
    "pkey_free"             : { "id": 331},
    "statx"                 : { "id": 332},
    "io_pgetevents"         : { "id": 333},
    "rseq"                  : { "id": 334},
    "SIGCHLD"               : { "id": 335, "threat": 6},
    "SIGPIPE"               : { "id": 336, "threat": 6},
}
